# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-09 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='modified'),
        ),
    ]
